repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
        exclude: "^.gitlab-ci.yml"
      # check-yaml against .gitlab-ci.yml using --unsafe because of their custom `!reference` tag
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
          - "--unsafe"
        files: "^.gitlab-ci.yml"
      - id: check-merge-conflict
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: no-commit-to-branch
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies:
          # This list should match is used for flake8 below
          - flake8-bugbear
          - pep8-naming
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args:
          - "--py312-plus"
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    # The `refs/tags/<tag>:refs/tags/<tag>` is needed for black's required-version to work:
    # https://github.com/psf/black/issues/2493#issuecomment-1081987650
    rev: "refs/tags/24.10.0:refs/tags/24.10.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        exclude: "^pytests/"
  - repo: https://github.com/andrei-shabanski/poetry-plugin-sort
    rev: v0.2.1
    hooks:
      - id: poetry-sort
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.4"
    hooks:
      - id: poetry-check
